# Generated by Django 5.1 on 2024-09-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_delete_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='dmy',
            field=models.DateField(),
        ),
    ]
